name: End-to-end tests 🧪
on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install Dependencies
        run: |
          npm ci
      - name: Install Cypress
        run: |
          npm install cypress@9.5.1
      - name: Cypress run
        run: |
          npx cypress run
