name: End-to-end tests 🧪

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Remove Node Modules
        run: rm -rf node_modules

      - name: Clear Cache
        run: |
          npm cache clean --force
          npx cypress cache clear

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install cypress@9.5.1

      - name: Verify Cypress Version
        run: npx cypress verify

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: false
          config-file: cypress.json
